name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
      - '[0-9]+.x'
    tags:
      - '*'
    paths-ignore:
      - 'docs/**'
      - '*.md'

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Deps
        run: |
          npm ci

      - name: Lint
        run: |
          npm run lint:ci

      - name: Build
        run: |
          npm run build

      - name: Tests
        run: |
          npm run test:ci
          npm run test:e2e:prepare
          npm run test:e2e

      - name: Coverage
        uses: codecov/codecov-action@v3
        timeout-minutes: 5
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage/coverage-final.json
          fail_ci_if_error: false

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    needs:
      - build

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        with:
          node-version: 16.x
          registry-url: 'https://registry.npmjs.org'
          cache: 'npm'

      - name: Deps
        run: |
          npm ci

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public

      - name: Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: contains(github.ref, '-')

  deploy:
    needs:
      - build
      - release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node
        id: setup-node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'

      - name: Deps
        run: |
          npm i

      - name: Lint
        run: |
          npm run lint:ci

      - name: Build
        env:
          PUBLIC_URL: /react-web-starter/
          NODE_ENV: production
        run: |
          npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v2

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1

  automerge:
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - uses: fastify/github-action-merge-dependabot@v3.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
